### ISSUE TITLE
Add "Information from comments"

### ISSUE THREAD

**Issue by Nevarro** [dokufreaks/plugin-filelist#29]
What a great tool Dokuwiki and filelist are. 

I would like to add additional information about the files to the table. Would it be possible to add another option to display file comments? Mac OS offers me to add a comment to the file. For school, I could write down "Partner work, vocab training, ..." and my students would know what to expect in the .docx-file.

**Comment by Klap-in** [comment]
Is this information already stored in DokuWiki? Or in the file? Please give more background. If you have examples, please provide here.
