### ISSUE TITLE
Listing results not as expected

### ISSUE THREAD

**Issue by Openuser87** [dokufreaks/plugin-filelist#34]
Hi there,

**First:** Using:
`{{filelist>data/media/wiki/lectures/*&style=list&direct=1}}`

yields a list of mp3's in the folder. Though, the links are of the form `https://<site.domain>/data/media/wiki/lectures/<filename>.mp3`, and trying to click it to download a file **gives a "Forbidden" error in the browser.**

**Second:** Using:
`{{filelist>:wiki:lectures:*&style=list}}`

**gives an "n/a: access denied" error.**

Settings are the defaults:
![grafik](https://user-images.githubusercontent.com/78308306/113482845-beb2d000-94a0-11eb-880d-ef1fd7186391.png)

Regards

**Comment by splitbrain** [comment]
closing this as it no longer applies to current plugin versions
