### ISSUE TITLE
I want to list *.MID files but this type is not listed by the plugin

### ISSUE THREAD

**Issue by Floffyko** [dokufreaks/plugin-filelist#36]
Hi. I want to list *.MID files but this type is not listed by the plugin. The MIME type seems OK. What kind of settings do I have to do in order to make this file type visible? Thanks

**Comment by Klap-in** [comment]
How do I replicate your situation? Please add an example.

**Comment by splitbrain** [comment]
I am closing this. If the problem persists with an up to date plugin (and correct configuration) feel free to request a reopen.
