### ISSUE TITLE
Uppercase Namespace Breaks listing

### ISSUE THREAD

**Issue by ajshea** [dokufreaks/plugin-filelist#37]
It appears that filelist does not enforce lower-case on the namespace path before it attempts to enumerate the list.

When creating pages with bureaucracy plugin and the namespace path is substituted, if the data was entered in Mixed or UPPERCASE, filelist fails to find matching files ( [n/a: No match] )  Manually editing the page to convert the namespace path to lowercase works, but defeats the purpose of using a template to create pages etc. 

Indexmenu, gallery, nspages and other plugins handle this "case" without complaint.

Unfortunately, bureaucracy / dokuwiki namespace-template replacement patterns have mechanisms for upper-case adjustment, but not lower-case.

Example:

     {{filelist>:BI:KHH:dwg:*.pdf&style=table&tableheader=1&tableshowdate=1&tableshowsize=1}}

     [n/a: No match] 

The country code and project code are inserted into the new page by Bureaucracy "as is" from the data entry form.

**Comment by ajshea** [comment]
Here's a suggested fix, I can't do a patch & PR right now: 

syntax.php line 48: 
```
--  $match = substr($match, 2, -2);
++ $match = strtolower(substr($match, 2, -2));
```

**Comment by Klap-in** [comment]
As little addition, not sure if $match can contain characters of many languages, if so, then Phpstring::[strtolower](https://codesearch.dokuwiki.org/s?defs=strtolower&project=dokuwiki)() is recommended.

**Comment by splitbrain** [comment]
closing this since namespace listing is no longer supported by this plugin
