### ISSUE TITLE
filelist produces empty page, then error message

### ISSUE THREAD

**Issue by qhbeauftragter** [dokufreaks/plugin-filelist#47]
We are on DokuWiki 2024-02-06a "Kaos" and filelist-version 2024-04-03. This syntax worked in the past, but now produces a browser page with no content:
`{{filelist>:path:*.*&recursive=1&order=asc}}`

After a while this error message shows up:

```
dokuwiki\Exception\FatalException: Maximum execution time of 30 seconds exceeded
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the filelist plugin.
More info has been written to the DokuWiki error log.
```

I read that other syntax should work:
`{{filelist>:path:*&style=olist&sort=name&order=desc}}`

I tried this, but the result is the same (no page, later error message).

Please help (because I am no IT expert, nevertheless my job is to run a dokuwiki): 
Where do I find the error log (I use filezilla for server connection)? 
What entries should I look for? 
Might I post the entries in this thread so someone could give assistence?

**Comment by qhbeauftragter** [comment]
In the configuration manager of dokuwiki I went to section "filelist". For "plugin filelist paths" I entered the url for our dokuwiki like this:
https://doku.gswn.de

Now the resulting browser page is not empty, the expected content is shown. But no filelist. Instead the page reads 
[n/a: Zugriff verweigert]

So please help, what should I specify for "plugin filelist paths"?

**Comment by splitbrain** [comment]
Please read the documentation of the plugin. Namespace based paths are no longer supported. Your file path configuration is also not matching the required format.

**Comment by qhbeauftragter** [comment]
Well, yes I tried to RTFM ( F like fabulous), but based on my knowledge I found no solution (maybe an example in documentation would help). 

I hoped to get friendly and useful help here, but it seems the only solution is to switch to another plugin with broader acceptance.
